config/routes.rb
Miarroyo::Application.routes.draw do

  root to: "arroyos#index"
  devise_for :users, skip: [:registrations]

  resources :arroyos do
    collection do
      get 'get_points'
      post 'get_arroyo'
      get 'alternative'
    end
  end
  resources :points
  resources :sensors
  resources :gcm_users, only: [:create]
end

app/models/point.rb
class Point < ActiveRecord::Base

  acts_as_api

  attr_accessible :arroyo_id, :latitude, :longitude, :sensor_id, :alternative

  belongs_to :arroyo
  belongs_to :sensor

  default_scope order('id ASC')

  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :arroyo, presence: true

  scope :normal_points, where(alternative: nil)
  scope :alternative_points, where(alternative: true)

  geocoded_by :address, latitude: :latitude, longitude: :longitude
  after_validation :geocode

  api_accessible :basic_point do |t|
    t.add :latitude
    t.add :longitude
    t.add :arroyo_id
    t.add :to_pair
  end

  def address
    [self.latitude, self.longitude]
  end

  def to_pair
    resp = []
    resp[0] = latitude
    resp[1] = longitude
    resp[2] = id
    resp[3] = sensor_id

    resp
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit]

  def index
    @points = Point.find(:all, order: "arroyo_id")
    respond_to do |format|
      format.html
      format.json {render_for_api :basic_point, json: @points}
    end
  end

  def new
    @point = Point.new
  end

  def create
    @point = Point.new(params[:point])
    if @point.save
      flash.now[:notice] = "point added successfuly."
    else
      flash.now[:error] = "could not add the point."
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # def edit
  #   @point = Point.find(params[:id])
  # end

  def destroy
    @point = Point.find(params[:id])
    if @point.destroy
      redirect_to points_path, notice: "Point Deleted successfuly"
    else
      flash[:error] = @point.errors.full_messages.to_sentence
    end
  end

end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.haml
%h1= @point.new_record? ? "Agregar un nuevo punto" : "Editar punto de arroyo especifico"
.row-fluid
  .span9
    #map
  .span3
    = form_for @point, html:{multipart: true, class: "form-horizontal"}, remote: true do |f|
      %div
        = label_tag "Seleccionar un arroyo"
        = collection_select(:point, :arroyo_id, Arroyo.all, :id, :name, :prompt => true)
      %div.lat-lng{class: "#{@point.new_record? ? 'hidden' : ''}" }
        %div
          = f.label :latitude, "latitud"
          = f.text_field :latitude
        %div
          = f.label :longitude,"longitud"
          = f.text_field :longitude
        %div
          = f.check_box :alternative
          \ ruta alternativa?
        %br
        %div
          = f.submit "Agregar", class: "btn btn-primary"

= subscribe_to "/points/new"

app/views/points/create.js.erb
<% publish_to "/points/new" do %>
  <% if flash[:notice] %>
    $(".navbar").append("<div class='alert alert-success'>  Point added Succesfully </div>")
  <%end%>

  <% if flash[:error] %>
    $(".navbar").append("<div class='alert alert-error'>  Could not add point </div>")
  <%end%>

  $(".alert").fadeOut(6000, function() {
    $(this).remove
  });
<%end%>

app/views/points/edit_fake.html.haml
= render "form"

- content_for :javascript do
  = javascript_include_tag "points"

app/views/points/index.html.haml
= link_to "Agregar punto", new_point_path, {class: "btn btn-primary"} if current_user
%table.table.table-striped
  %thead
    %tr
      %th Latitud
      %th Longitud
      %th Arroyo
  %tbody
  - @points.each do |point|
    %tr
      %td= point.latitude
      %td= point.longitude
      %td= point.arroyo.name
      %td
        - if current_user
          = link_to point_path(point.id), method: "delete" do
            =image_tag("delete.png")

- content_for :javascript do
  = javascript_include_tag "points"

app/views/points/new.html.haml
= render "form"

- content_for :javascript do
  = javascript_include_tag "points"

= subscribe_to "/arroyos/index"