config/routes.rb
Miarroyo::Application.routes.draw do

  root to: "arroyos#index"
  devise_for :users, skip: [:registrations]

  resources :arroyos do
    collection do
      get 'get_points'
      post 'get_arroyo'
      get 'alternative'
    end
  end
  resources :points
  resources :sensors
  resources :gcm_users, only: [:create]
end

app/views/shared/_alerts.html.haml
- if flash[:notice]
  .alert.alert-success
    =flash[:notice]

- if flash[:error]
  .alert.alert-error
    =flash[:error]

app/views/shared/_footer.html.haml
.footer-sat
  %table 
    %tr
      %td Proyecto de grado, simulación sistema de alertas tempranas (SAT)
    %tr
      %td Unversidad de la costa CUC
    %tr
      %td Luis Rodriguez, Diego Hernandez
    %tr  
      %td Barranquilla - Colombia

    

app/views/shared/_header.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container.color-cuc
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        = link_to root_path, class: "brand" do
          =image_tag("cuc2.png")
      .nav-collapse.collapse
        %ul.nav
          - if user_signed_in?
            %li
              = link_to "Nuevo arroyo", new_arroyo_path
          %li
            = link_to "Puntos", points_path
          %li
            = link_to "Sensor", sensors_path
          %li
            <a href="#myModal" data-toggle="modal">Acerca de la aplicación</a>

        - if user_signed_in?
          %ul.nav.pull-right
            %li
              = link_to "Salir", destroy_user_session_path, method: :delete
            %li
              = link_to "Administrador", "" 
        - unless user_signed_in?
          %ul.nav.pull-right
            %li
              = link_to "Iniciar sesión", new_user_session_path