config/routes.rb
Miarroyo::Application.routes.draw do

  root to: "arroyos#index"
  devise_for :users, skip: [:registrations]

  resources :arroyos do
    collection do
      get 'get_points'
      post 'get_arroyo'
      get 'alternative'
    end
  end
  resources :points
  resources :sensors
  resources :gcm_users, only: [:create]
end

app/models/arroyo.rb
class Arroyo < ActiveRecord::Base

  acts_as_api

  has_many :sensors, dependent: :destroy
  has_many :points, dependent: :destroy

  attr_accessible :address,
                  :name,
                  :points_attributes

  scope :by_date_range, ->(range) { where("updated_at between ? and ?", range.split("|")[0].to_s.to_time, range.split("|")[1].to_s.to_time) }

  validates :name, presence: true

  api_accessible :basic_arroyo do |t|
    t.add :id
    t.add :address
    t.add :name
    t.add :all_points
    t.add :all_sensors
  end

  accepts_nested_attributes_for :points, allow_destroy: true
  accepts_nested_attributes_for :sensors, allow_destroy: true

  def all_points
    results = []
    self.points.each do |point|
      if !point.alternative
        results << point.to_pair
      end
    end
    results
  end

  def all_sensors
    results = []
    self.sensors.each do |sensor|
      results << sensor.make
    end
    results
  end
end

app/controllers/arroyos_controller.rb
class ArroyosController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit]

  def index
    if params[:range]
      @arroyos = Arroyo.by_date_range(params[:range])
    else
      @arroyos = Arroyo.find(:all, include: [:points, :sensors])
    end
    respond_to do |format|
      format.html
      format.json {render_for_api :basic_arroyo, json: @arroyos}
    end
  end

  def new
    @arroyo = Arroyo.new
  end

  def edit
    @arroyo = Arroyo.find(params[:id])
  end

  def update
      @arroyo = Arroyo.find(params[:id])
    if @arroyo.update_attributes(params[:arroyo])
      flash.now[:notice] = "Arroyo actuailzado correctamente"
      redirect_to(root_path)
    else
      flash.now[:error] = "No se puede actualizar el arroyo"
      render :edit
    end
  end

  def create
    @arroyo = Arroyo.new(params[:arroyo])
    if @arroyo.save
      redirect_to root_path
    else
      flash.now[:error] = "No se puede agregar el arroyo"
    end
  end

  def destroy
    @arroyo = Arroyo.find(params[:id])
    @arroyo.destroy
    redirect_to root_path
  end

  def get_points
    @resp = {}
    Arroyo.all.each_with_index do |arroyo, index|
      @resp["points_#{index}"] = arroyo.all_points
      @resp["sensors_#{index}"] = arroyo.all_sensors
    end
    @resp
    respond_to do |format|
      format.html
      format.json {render json: @resp}
      format.mobile {render json: @resp}
    end
  end

  def get_arroyo
    @resp = {}
    arroyo = Arroyo.find(params[:arroyo])
    @resp["points"] = arroyo.all_points
    if params[:sensor].present?
      @resp["sensors"] = Sensor.find(params[:sensor]).make
    else
      @resp["sensors"] = arroyo.all_sensors
    end
    @resp
    respond_to do |format|
      format.html
      format.json {render json: @resp}
      format.mobile {render json: @resp}
    end
  end

  def alternative
    @points = Point.alternative_points.near(params[:origin], 20).first(2)
    respond_to do |format|
      format.json {render json: @points}
    end
  end
end

app/helpers/arroyos_helper.rb
module ArroyosHelper
end

app/views/arroyos/_form.html.haml
%h1= @arroyo.new_record? ? "Nuevo Arroyo" : "Edit Arroyo"
%h5.subtitle Arroyos
.row-fluid
  .span9
    #map
  .span3
    = form_for @arroyo, html:{multipart: true, class: "form-horizontal"} do |f|
      %div
        = f.label :address, "Direccion"
        = f.text_field :address 
      %div
        = f.label :name, "Nombre"
        = f.text_field :name
      %div
        %br
        = f.submit "Guardar", class: "btn btn-primary"

= subscribe_to "/points/new"

app/views/arroyos/edit.html.haml
= render "form"

- content_for :javascript do
  = javascript_include_tag "arroyos"
  = javascript_include_tag "arroyos_new"
  = javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"

= subscribe_to "/arroyos/index"

app/views/arroyos/get_arroyo.json.erb
<%= @resp %>

app/views/arroyos/get_points.json.erb
<%= @resp %>

app/views/arroyos/index.html.haml
%h3.fuck Sistema de alertas tempranas de los arroyos en la ciudad de Barranquilla SATAB
%a{id: "list-arroyos", href: "javascript:;", data: "show"} Listar todos los arroyos
%fieldset
  = collection_select(:arroyo, :arroyo_id, Arroyo.all, :id, :name, :prompt => "Todos los arroyos")

  .js-origin-fields.hidden
    = text_field_tag :user_origin, nil, class: "js-user-lat-origin"
    = text_field_tag :user_destination, nil, class: "js-user-lng-origin"

  .js-destination-fields.hidden
    = text_field_tag :user_origin, nil, class: "js-user-lat-destination"
    = text_field_tag :user_destination, nil, class: "js-user-lng-destination"

  %button.btn.btn-primary.hidden.js-get-alternative-route Rutas alternas
  %button.btn.btn-primary.hidden.js-clean-alternative-route Limpiar Rutas

#map.map
#legend
  = image_tag("markers.png")

#list-arroyos.hidden
  %h2 lista de arroyos
  = link_to "Agregar arroyo", new_arroyo_path, {class: "btn btn-primary"} if current_user
  %table.table.table-striped
    %thead
      %tr
        %th Nombre
        %th Direccion
    %tbody
    - @arroyos.each do |arroyo|
      %tr
        %td= arroyo.name
        %td= arroyo.address
        - if current_user
          %td
            = link_to edit_arroyo_path(arroyo) do
              = image_tag("edit.png")
          %td
            = link_to arroyo_path(arroyo.id), method: "delete" do
              = image_tag("delete.png")

- content_for :javascript do
  = javascript_include_tag "arroyos"

= subscribe_to "/points/new"

app/views/arroyos/new.html.haml
= render "form"

- content_for :javascript do
  = javascript_include_tag "arroyos"
  = javascript_include_tag "arroyos_new"
  = javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"

= subscribe_to "/arroyos/index"