config/routes.rb
Miarroyo::Application.routes.draw do

  root to: "arroyos#index"
  devise_for :users, skip: [:registrations]

  resources :arroyos do
    collection do
      get 'get_points'
      post 'get_arroyo'
      get 'alternative'
    end
  end
  resources :points
  resources :sensors
  resources :gcm_users, only: [:create]
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base

  include PushNotification
  include ReadSensorsXML
  acts_as_api

  attr_accessible :arroyo_id, :latitude, :longitude, :status, :external_id

  default_scope order('id ASC')

  belongs_to :arroyo
  has_many :points

  STATUS_OPTIONS = ["good", "bad", "medium"]

  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :status, presence: true
  validates :status, inclusion: {:in => STATUS_OPTIONS}

  before_save :refresh_google_maps
  #after_save :send_push_notification, :if => Proc.new {|obj| obj.status_changed? }

  api_accessible :basic_sensor do |t|
    t.add :latitude
    t.add :longitude
    t.add :status
    t.add :arroyo_id
    t.add :make
  end

  def make
    resp = []
    resp[0] = latitude
    resp[1] = longitude
    resp[2] = status
    resp[3] = id
    resp
  end

  def refresh_google_maps
    PrivatePub.publish_to("/points/new", "console.log('sensor updated');")
  end

  private
    def is_bad?
      self.status == 'bad' ? true : false
    end

    def is_good
      self.status == 'good' ? true : false
    end

    def is_medium
      self.status == 'medium' ? true : false
    end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :destroy]

  def index
    @sensors = Sensor.find(:all, order: "arroyo_id")
    respond_to do |format|
      format.html
      format.json {render_for_api :basic_sensor, json: @sensors}
    end
  end

  def new
    @sensor = Sensor.new
  end

  def create
    @sensor = Sensor.new(params[:sensor])
    if @sensor.save
      flash.now[:notice] = "Sensor added successfuly."
    else
      flash.now[:error] = "Could not add Sensor."
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @sensor = Sensor.find(params[:id])
  end

  def update
    @sensor = Sensor.find(params[:id])
    if @sensor.update_attributes(params[:sensor])
      flash.now[:notice] = "sensor added successfuly."
    else
      flash.now[:error] = "could not update the sensor."
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @sensor = Sensor.find(params[:id])
    if @sensor.destroy
      redirect_to sensors_path, notice: "Sensor Deleted successfuly"
    else
      flash[:error] = @sensor.errors.full_messages.to_sentence
    end
  end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.haml
%h1= @sensor.new_record? ? "Agregar un nuevo sensor" : "Editar sensor"
%h5.subtitle{"data-sensor-id" => params[:id] }= "Para editar, porfavor mover el cursor a su nueva posición" unless @sensor.new_record?
.row-fluid
  .span9
    #map
  .span3
    = form_for @sensor, html:{multipart: true, class: "form-horizontal"}, remote: true do |f|
      %div
        = label_tag "Seleccionar arroyo"
        = collection_select(:sensor, :arroyo_id, Arroyo.all, :id, :name, :prompt => true)
      %div.lat-lng{class: "#{@sensor.new_record? ? 'hidden' : ''}" }
        %div
          = f.label :latitude, "latitud"
          = f.text_field :latitude
        %div
          = f.label :longitude, "Longitud"
          = f.text_field :longitude
        %div
          = f.label :status, "Estado"
          = f.select :status, Sensor::STATUS_OPTIONS, {prompt: 'Select Status'}
        %div
          = f.label :external_id, "Serial"
          = f.text_field :external_id
        %div
          = f.submit "Guardar", class: "btn btn-primary"

= subscribe_to "/points/new"

app/views/sensors/create.js.erb
<% publish_to "/points/new" do %>
  <% if flash[:notice] %>
    $(".navbar").append("<div class='alert alert-success'>  Sensor added Succesfully </div>")
  <%end%>

  <% if flash[:error] %>
    $(".navbar").append("<div class='alert alert-error'>  Could not add Sensor </div>")
  <%end%>

  $(".alert").fadeOut(6000, function() {
    $(this).remove
  });
<%end%>

app/views/sensors/edit.html.haml
= render "form"

- content_for :javascript do
  = javascript_include_tag "edit_sensors"

app/views/sensors/index.html.haml
= link_to "Agregar", new_sensor_path, {class: "btn btn-primary"} if current_user
%table.table.table-striped
  %thead
    %tr
      %th Latitud
      %th Longitud
      %th Estado
      %th Arroyo
  %tbody
  - @sensors.each do |sensor|
    %tr
      %td= sensor.latitude
      %td= sensor.longitude
      %td= sensor.status
      %td= sensor.arroyo.name
      - if current_user
        %td
          = link_to edit_sensor_path(sensor) do
            =image_tag("edit.png")
        %td
          = link_to sensor_path(sensor.id), method: "delete" do
            =image_tag("delete.png")



- content_for :javascript do
  = javascript_include_tag "sensors"

app/views/sensors/new.html.haml
= render "form"

- content_for :javascript do
  = javascript_include_tag "sensors"

= subscribe_to "/arroyos/index"

app/views/sensors/update.js.erb
<% publish_to "/points/new" do %>
  <% if flash[:notice] %>
    $(".navbar").append("<div class='alert alert-success'>  Sensor updated Succesfully </div>")
  <%end%>

  <% if flash[:error] %>
    $(".navbar").append("<div class='alert alert-error'>  Could not update Sensor </div>")
  <%end%>

  $(".alert").fadeOut(6000, function() {
    $(this).remove
  });
<%end%>